PINECONE_API_KEY_CONTENT = "b183d65d-9501-483a-82e7-8e86f9eb46ce"
PINECONE_API_KEY_EMOTION = "2d619f01-148b-4a3a-9bbf-4b8211f8409d"

EMOTIONS = ['Admiration',
 'Adoration',
 'Aesthetic Appreciation',
 'Amusement',
 'Anger',
 'Annoyance',
 'Anxiety',
 'Awe',
 'Awkwardness',
 'Boredom',
 'Calmness',
 'Concentration',
 'Confusion',
 'Contemplation',
 'Contempt',
 'Contentment',
 'Craving',
 'Desire',
 'Determination',
 'Disappointment',
 'Disapproval',
 'Disgust',
 'Distress',
 'Doubt',
 'Ecstasy',
 'Embarrassment',
 'Empathic Pain',
 'Enthusiasm',
 'Entrancement',
 'Envy',
 'Excitement',
 'Fear',
 'Gratitude',
 'Guilt',
 'Horror',
 'Interest',
 'Joy',
 'Love',
 'Nostalgia',
 'Pain',
 'Pride',
 'Realization',
 'Relief',
 'Romance',
 'Sadness',
 'Sarcasm',
 'Satisfaction',
 'Shame']